### ISSUE TITLE
Newest version gspread not compatible

### ISSUE THREAD

**Issue by RalphSchuurman** [robin900/gspread-dataframe#55]
Gspread 6.0.0 was released yesterday and has some breaking changes with gspread-dataframe it seems.
Code:

```
from gspread_dataframe import get_as_dataframe, set_with_dataframe
service_account = gspread.service_account(filename = "xxx.json")
spreadsheet = service_account.open("SPREADSHEET")
mapping_id = spreadsheet.worksheet("WORKSHEET")
df = get_as_dataframe(mapping_id)
```

AttributeError: 'Worksheet' object has no attribute 'spreadsheet'

I think it is due to a change in gspread, that there exist no .spreadsheet attribute anymore in the Worksheet object. For anyone having the same issue, setting gspread back to 5.12.4 works.

**Comment by isdabenx** [comment]
I'm encountering the same issue. It's worth noting that this isn't the only project using `gspread` that's running into trouble. It seems there were some significant changes between version 5 and version 6 that are leading to these breakdowns. For the time being, I have also chosen to revert back to version 5.12.4 to maintain functionality.

https://github.com/burnash/gspread/issues/1395

**Comment by RaptorRob** [comment]
Same here. For the time being working with gspread 5.12.

**Comment by jianchen1628** [comment]
+1

**Comment by karpp** [comment]
+1

**Comment by griggem** [comment]
+1 and also the gspread docs have a pseudo- get_as_dataframe and set_with_dataframe [here](https://docs.gspread.org/en/latest/user-guide.html#using-gspread-with-pandas)

**Comment by robin900** [comment]
Gspread just released 6.0.1 to correct the breakage with 6.0.0. You may wish to test with 6.0.1...

**Comment by robin900** [comment]
Other issue reported the same, and confirmed that gspread 6.0.1 fixes the issue. Closing this...
